version: '3.8'
services:
  kairos_redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: kairos_redpanda
    restart: unless-stopped
    command:
      - redpanda start
      - --smp 1
      - --memory 2G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --check=false
      - --kafka-addr=0.0.0.0:9092
      - --advertise-kafka-addr=kairos_redpanda:9092
    ports:
      - "9092:9092"
    volumes:
      - /mnt/volume_nyc3_01/redpanda_data:/var/lib/redpanda/data

  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    restart: unless-stopped
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - /mnt/volume_nyc3_01/clickhouse_data:/var/lib/clickhouse
      - ./reset_password.xml:/etc/clickhouse-server/users.d/reset_password.xml
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  kairos_aggregator:
    build: 
      context: ./aggregator
    container_name: kairos_aggregator
    restart: unless-stopped
    depends_on:
      - kairos_redpanda
      - clickhouse-server
    environment:
      - CH_HOST=clickhouse-server
      - CH_PASS=kairos
      - KAFKA_BROKER=kairos_redpanda:9092

  kairos_dashboard:
    image: grafana/grafana:latest
    container_name: kairos_dashboard
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
      - GF_SECURITY_ADMIN_PASSWORD=kairos
    depends_on:
      - clickhouse-server
